from typing import Protocol

from src.domain.common.value_objects.ids import BookId, ChapterDigestId, ChapterId
from src.domain.reading.entities.chapter_digest import ChapterDigest


class ChapterDigestRepositoryProtocol(Protocol):
    async def find_by_id(self, id: ChapterDigestId) -> ChapterDigest | None: ...
    async def find_by_chapter_id(self, chapter_id: ChapterId) -> ChapterDigest | None: ...
    async def find_all_by_book_id(self, book_id: BookId) -> list[ChapterDigest]: ...
    async def save(self, content: ChapterDigest) -> ChapterDigest: ...
    async def delete(self, id: ChapterDigestId) -> None: ...
